### ISSUE TITLE
Add `Gatsby` setup page

### ISSUE THREAD

**Issue by hirotomoyamada** [hirotomoyamada/yamada-docs#147]
### Subject

getting-started/frameworks/gatsby

### Description

We want to create a `Yamada UI` setup page using `Gatsby`.

### Are you willing to participate in creating this documentation page and create a pull request?

None

**Comment by kinjo1130** [comment]
I would like to do it!

**Comment by hirotomoyamada** [comment]
@kinjo1130 

Thanks!
