### ISSUE TITLE
`ColorModeScript`がReactで埋め込めない問題

### ISSUE THREAD

**Issue by illionillion** [hirotomoyamada/yamada-docs#162]
### エラーまたは問題の正確な引用

以下のコードで、`ColorModeScript`が埋め込めない。
原因としては、内部で実行されている`<script>`の埋め込みがhead内に最初に埋め込まれていないから。
解決するには、`ColorModeScript`をReactの管轄外にするなどして、head内に埋め込む実装に変える必要がある。

これを実装するか、ドキュメントの[このページ](https://yamada-ui.com/ja/styled-system/color-mode#create-react-app%E3%81%AE%E5%A0%B4%E5%90%88)の部分を削除する。

![image](https://github.com/hirotomoyamada/yamada-docs/assets/60034520/530d961a-6517-41c2-a2fd-c581bb55f162)

### この問題の修正に参加し、修正を含むプルリクエストを作成する志はありますか？

None

**Comment by hirotomoyamada** [comment]
`ColorModeScript`ではなく、`getColorModeScript`を使う必要があります。ドキュメントを修正する必要があります。

```tsx
import { createRoot } from "react-dom/client"
import { App } from "./app"
import { UIProvider, getColorModeScript } from "@yamada-ui/react"
import { theme, config } from "theme"

const injectColorModeScript = () => {
  const scriptContent = getColorModeScript({
    initialColorMode: config.initialColorMode,
  })

  const script = document.createElement("script")

  script.textContent = scriptContent

  document.head.appendChild(script)
}

injectColorModeScript()

const container = document.getElementById("app")

const root = createRoot(container!)

root.render(
  <UIProvider theme={theme} config={config}>
    <App />
  </UIProvider>,
)
```

**Comment by hirotomoyamada** [comment]
Fixed #163
